# Builds project (with various compilers, CMake options, etc.) and runs tests
name: BasicBuilds

on: [push, pull_request]

permissions:
  contents: read

jobs:
  macos-build:
    name: MacOS
    strategy:
      matrix:
        # os: ['macos-12', 'macos-13']
        os: ['macos-13']
    env:
      BUILD_DIR : "${{github.workspace}}/build/"
      INSTL_DIR : "${{github.workspace}}/../install-dir"
      BUILD_TYPE : "Release"
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install Python requirements
      run: python3 -m pip install -r third_party/requirements.txt

    - name: Install hwloc
      run: brew install hwloc jemalloc tbb

    - name: Configure build
      run: >
        cmake
        -B ${{env.BUILD_DIR}}
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DUMF_FORMAT_CODE_STYLE=OFF
        -DUMF_DEVELOPER_MODE=ON
        -DUMF_ENABLE_POOL_TRACKING=ON
        -DUMF_BUILD_LEVEL_ZERO_PROVIDER=OFF
        -DUMF_BUILD_LIBUMF_POOL_DISJOINT=ON
        -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=ON
        -DUMF_BUILD_LIBUMF_POOL_SCALABLE=ON
        -DUMF_BUILD_SHARED_LIBRARY=ON

    - name: Build UMF
      run: cmake --build ${{env.BUILD_DIR}} -j $(sysctl -n hw.logicalcpu)

    - name: Run tests
      working-directory: ${{env.BUILD_DIR}}
      run: ctest --output-on-failure --test-dir test

    - name: Test UMF installation and uninstallation
      run: >
        python3 ${{github.workspace}}/test/test_installation.py
        --build-dir ${{env.BUILD_DIR}}
        --install-dir ${{env.INSTL_DIR}}
        --build-type ${{env.BUILD_TYPE}}
        --shared-library
        --disjoint-pool
        --jemalloc-pool
        --scalable-pool
