name: GitHubActions

on: [push, pull_request]

jobs:
  macos-build:
    name: Build - MacOS
    strategy:
        matrix:
          os: ['macos-12', 'macos-13']
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install brew packages
        run: |
          find /usr/ -name threads.h || echo "threads.h not found!"
          brew install libc6-dev || echo "libc6-dev not found!"
          brew install libccd || echo "libccd not found!"
          find /usr/ -name threads.h

      - name: Install Python requirements
        run: python3 -m pip install -r third_party/requirements.txt

      - name: Configure build
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=Release
          -DUMF_FORMAT_CODE_STYLE=ON
          -DUMF_DEVELOPER_MODE=ON
          -DUMF_ENABLE_POOL_TRACKING=ON

      - name: Run code-style check     
        run: |
          cmake --build ${{github.workspace}}/build --target clang-format-check

      - name: Build UMF
        run: |
          cmake --build ${{github.workspace}}/build -j $(sysctl -n hw.logicalcpu)
