# Builds project (with various compilers, CMake options, etc.) and runs tests
name: BasicBuilds

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ubuntu-build:
    name: Ubuntu
    strategy:
      matrix:
        include:
          - os: 'ubuntu-22.04'
            build_type: Debug
            compiler: {c: gcc, cxx: g++}
            shared_library: 'ON'
            pool_tracking: 'ON'
            level_zero_provider: 'ON'
    env:
      BUILD_DIR : "${{github.workspace}}/build/"
      INSTL_DIR : "${{github.workspace}}/../install-dir"
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake libhwloc-dev libnuma-dev libjemalloc-dev libtbb-dev

    - name: Install g++-7
      if: matrix.compiler.cxx == 'g++-7'
      run: sudo apt-get install -y ${{matrix.compiler.cxx}}

    - name: Configure build
      run: >
        cmake
        -B ${{env.BUILD_DIR}}
        -DCMAKE_INSTALL_PREFIX="${{env.INSTL_DIR}}"
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DUMF_BUILD_SHARED_LIBRARY=${{matrix.shared_library}}
        -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        -DUMF_BUILD_LEVEL_ZERO_PROVIDER=${{matrix.level_zero_provider}}
        -DUMF_ENABLE_POOL_TRACKING=${{matrix.pool_tracking}}
        -DUMF_FORMAT_CODE_STYLE=OFF
        -DUMF_DEVELOPER_MODE=ON
        -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=ON
        -DUMF_BUILD_LIBUMF_POOL_DISJOINT=ON
        -DUMF_BUILD_LIBUMF_POOL_SCALABLE=ON

    - name: Build UMF
      run: cmake --build ${{env.BUILD_DIR}} -j $(nproc)

    - name: Run tests
      working-directory: ${{env.BUILD_DIR}}
      run: ctest -V --test-dir test -R proxy_lib_basic

    - name: Test UMF installation and uninstallation
      # The '--shared-library' parameter is added to the installation test when the UMF is built as a shared library
      run: >
        python3 ${{github.workspace}}/test/test_installation.py
        --build-dir ${{env.BUILD_DIR}}
        --install-dir ${{env.INSTL_DIR}}
        --build-type ${{matrix.build_type}}
        --disjoint-pool
        --jemalloc-pool
        --scalable-pool
        ${{ matrix.shared_library == 'ON' && '--shared-library' || '' }}
