# Coverage build
name: Coverage

on: workflow_call

permissions:
  contents: read

env:
  BUILD_DIR : "${{github.workspace}}/build"
  INSTL_DIR : "${{github.workspace}}/../install-dir"
  COVERAGE_DIR : "${{github.workspace}}/coverage"

jobs:
  Coverage:
    name: Coverage build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Install dependencies (ubuntu-latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libjemalloc-dev libhwloc-dev libnuma-dev libtbb-dev lcov

      # Latest distros do not allow global pip installation
      - name: Install Python requirements in venv
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          echo "$PATH" >> $GITHUB_PATH
          python3 -m pip install gcovr

      - name: Set ptrace value for IPC test
        run: sudo bash -c "echo 0 > /proc/sys/kernel/yama/ptrace_scope"

      - name: Configure CMake
        run: >
          cmake
          -B ${{env.BUILD_DIR}}
          -DCMAKE_INSTALL_PREFIX="${{env.INSTL_DIR}}"
          -DCMAKE_BUILD_TYPE=Debug
          -DUMF_BUILD_SHARED_LIBRARY=ON
          -DUMF_TESTS_FAIL_ON_SKIP=ON
          -DUMF_USE_COVERAGE=ON

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config Debug -j

      - name: Run tests
        working-directory: ${{env.BUILD_DIR}}
        run: |
          ctest --output-on-failure
  
      - name: Check coverage
        working-directory: ${{env.BUILD_DIR}}
        run: |
          export FILE_NAME=exports-coverage-last
          ../scripts/coverage/coverage_capture.sh $FILE_NAME
          mkdir -p ${{env.COVERAGE_DIR}}
          mv ./$FILE_NAME ${{env.COVERAGE_DIR}}

      - name: Download file exports-coverage-basic-ubuntu-20.04-shared-OFF-hwloc-OFF
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-20.04-shared-OFF-hwloc-OFF
          path: coverage

      - name: Download file exports-coverage-basic-ubuntu-22.04-shared-OFF-hwloc-OFF
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-22.04-shared-OFF-hwloc-OFF
          path: coverage

      - name: Download file exports-coverage-basic-ubuntu-24.04-shared-ON-hwloc-OFF
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-24.04-shared-ON-hwloc-OFF
          path: coverage

      - name: Download file exports-coverage-basic-ubuntu-22.04-shared-ON-hwloc-ON
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-22.04-shared-ON-hwloc-ON
          path: coverage

      - name: Compute coverage
        working-directory: ${{env.COVERAGE_DIR}}
        run: |
          echo "DIR: $(pwd)" && ls -al
          gcovr --json-add-tracefile "exports-coverage-*" --html-details total_coverage.html
          gcovr --json-add-tracefile "exports-coverage-*" --txt
          # ../scripts/coverage/merge_coverage_files.sh total_coverage
          # genhtml --ignore-errors source -o html_report total_coverage 2>&1 | tee output.txt
          # tail -n3 output.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: coverage_html_report
          path: coverage/total_coverage.html
