# Coverage build
name: Coverage

on: workflow_call

permissions:
  contents: read

env:
  BUILD_DIR : "${{github.workspace}}/build"
  INSTL_DIR : "${{github.workspace}}/../install-dir"
  COVERAGE_DIR : "${{github.workspace}}/coverage"

jobs:
  Coverage:
    name: Coverage build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Install dependencies (ubuntu-latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Download file exports-coverage-basic-ubuntu-20.04-shared-OFF-hwloc-OFF
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-20.04-shared-OFF-hwloc-OFF
          path: coverage

      - name: Download file exports-coverage-basic-ubuntu-22.04-shared-OFF-hwloc-OFF
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-22.04-shared-OFF-hwloc-OFF
          path: coverage

      - name: Download file exports-coverage-basic-ubuntu-24.04-shared-ON-hwloc-OFF
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-24.04-shared-ON-hwloc-OFF
          path: coverage

      - name: Download file exports-coverage-basic-ubuntu-22.04-shared-ON-hwloc-ON
        uses: actions/download-artifact@v4
        with:
          name: exports-coverage-basic-ubuntu-22.04-shared-ON-hwloc-ON
          path: coverage

      - name: Compute coverage
        working-directory: ${{env.COVERAGE_DIR}}
        run: |
          echo "DIR: $(pwd)" && ls -al
          ../scripts/coverage/merge_coverage_files.sh exports-coverage total_coverage
          genhtml --ignore-errors source -o html_report total_coverage 2>&1 | tee output.txt
          tail -n3 output.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: coverage_html_report
          path: coverage/html_report
