# Fast builds
name: FastBuild

on: workflow_call

permissions:
  contents: read

env:
  BUILD_DIR : "${{github.workspace}}/build"
  INSTL_DIR : "${{github.workspace}}/../install-dir"

jobs:
  FastBuild:
    name: Fast builds
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            disjoint: 'OFF'
            build_tests: 'ON'
            extra_build_options: '-DCMAKE_BUILD_TYPE=Release'
            simple_cmake: 'ON'
    runs-on: ${{ (matrix.os == 'ubuntu-latest' && github.repository_owner == 'oneapi-src') && 'intel-ubuntu-22.04' || matrix.os }}

    steps:

    - name: Checkout repository
      run: echo "AKUKU ;-)"
