# Various non-standard tests, requiring e.g. longer run
name: Nightly

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  BUILD_DIR : "${{github.workspace}}/build"
  INSTALL_DIR: "${{github.workspace}}/build/install"

jobs:
  # Full execution of QEMU tests
  QEMU:
    uses: ./.github/workflows/reusable_qemu.yml
    with:
      short_run: false
      # Beside the 2 LTS Ubuntu, we also test this on the latest Ubuntu -  to be updated
      # every 6 months, so we verify the latest version of packages (compilers, etc.).
      os: "['ubuntu-22.04', 'ubuntu-24.04', 'ubuntu-25.04']"
