# Various non-standard tests, requiring e.g. longer run
name: Nightly

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  contents: read

env:
  BUILD_DIR : "${{github.workspace}}/build"
  INSTALL_DIR: "${{github.workspace}}/build/install"

jobs:
  SYCL:
    uses: ./.github/workflows/reusable_sycl.yml
