# Run checks required for a PR to merge and verify if post-merge commit is valid.
# This workflow only call other workflows.
name: PR/push

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  CodeChecks:
    uses: ./.github/workflows/reusable_checks.yml
  DocsBuild:
    uses: ./.github/workflows/reusable_docs_build.yml
  FastBuild:
    name: Fast builds
    needs: [CodeChecks, DocsBuild]
    uses: ./.github/workflows/reusable_fast.yml
  Build:
    name: Basic builds
    needs: [FastBuild]
    uses: ./.github/workflows/reusable_basic.yml
  DevDax:
    needs: [CodeChecks, DocsBuild]
    uses: ./.github/workflows/reusable_dax.yml
  ProxyLib:
    needs: [FastBuild]
    uses: ./.github/workflows/reusable_proxy_lib.yml
  GPU:
    needs: [Build]
    uses: ./.github/workflows/reusable_gpu.yml
  MultiNuma:
    needs: [Build]
    uses: ./.github/workflows/reusable_multi_numa.yml
  Coverage:
    # total coverage (on upstream only)
    if: github.repository == 'oneapi-src/unified-memory-framework'
    needs: [Build, DevDax, GPU, MultiNuma, ProxyLib]
    uses: ./.github/workflows/reusable_coverage.yml
  Coverage_partial:
    # partial coverage (on forks)
    if: github.repository != 'oneapi-src/unified-memory-framework'
    needs: [Build, ProxyLib]
    uses: ./.github/workflows/reusable_coverage.yml
