# Run checks required for a PR to merge and verify if post-merge commit is valid.
# This workflow only call other workflows.
name: PR/push

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  DevDax:
    uses: ./.github/workflows/reusable_dax.yml
  MultiNuma:
    uses: ./.github/workflows/reusable_multi_numa.yml
  L0:
    uses: ./.github/workflows/reusable_gpu.yml
    with:
      provider: "LEVEL_ZERO"
      runner: "L0"
      shared_lib: "['ON']"
  L0-BMG:
    uses: ./.github/workflows/reusable_gpu.yml
    with:
      provider: "LEVEL_ZERO"
      runner: "L0-BMG"
      shared_lib: "['ON']"
      os: "['Ubuntu']"
  CUDA:
    uses: ./.github/workflows/reusable_gpu.yml
    with:
      provider: "CUDA"
      runner: "CUDA"
      shared_lib: "['ON']"
  Sanitizers:
    uses: ./.github/workflows/reusable_sanitizers.yml
  QEMU:
    uses: ./.github/workflows/reusable_qemu.yml
    with:
      short_run: true
  ProxyLib:
    uses: ./.github/workflows/reusable_proxy_lib.yml
