# Run checks required for a PR to merge and verify if post-merge commit is valid.
# This workflow only call other workflows.
name: PR/push

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  Compatibility:
    uses: ./.github/workflows/reusable_compatibility.yml
    strategy:
      matrix:
        tag: ["v0.12.0-dev3"]
    with:
      tag: ${{matrix.tag}}
