# Build and push Docker images to GHCR
name: BuildDockers

on: 
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs: 
  build-dockers:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    env:
      IMG: ghcr.io/bb-ur/umf-${{ matrix.os }}:latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Build ${{ matrix.os }} Docker image
        run: |
          docker build -f .github/docker/${{ matrix.os }}.Dockerfile -t ${{ env.IMG }} .

      # Login and push require login/pass to GHCR - omit these steps on forks
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' && github.repository == 'oneapi-src/unified-memory-framework' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: bb-ur
          password: ${{ secrets.BB_GHCR_TOKEN }}

      - name: Push ${{ matrix.os }} Docker image
        if: ${{ github.event_name != 'pull_request' && github.repository == 'oneapi-src/unified-memory-framework' }}
        run: |
          docker push ${{ env.IMG }}
