# Run tests with valgrind instrumentation tools: memcheck, drd, helgrind
name: Valgrind

on: workflow_call

permissions:
  contents: read

jobs:
  valgrind:
    name: Valgrind (${{matrix.tool}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: ['memcheck', 'drd', 'helgrind']

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake hwloc libhwloc-dev libnuma-dev libtbb-dev valgrind

    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=Debug
        -DUMF_FORMAT_CODE_STYLE=OFF
        -DUMF_DEVELOPER_MODE=OFF
        -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=ON
        -DUMF_BUILD_LEVEL_ZERO_PROVIDER=OFF
        -DUMF_BUILD_CUDA_PROVIDER=OFF
        -DUMF_USE_VALGRIND=1
        -DUMF_TESTS_FAIL_ON_SKIP=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug -j$(nproc)

    - name: Run valgrind tests
      run: while ${{github.workspace}}/test/test_valgrind.sh ${{github.workspace}} ${{github.workspace}}/build ${{matrix.tool}} ; do date ; done && exit 1
